server:
  port: 8083

spring:
  datasource:
    url: jdbc:mysql://localhost:3306
    username: root
    password: admin
  application:
    name: twilio-service

appDescription: "Pragma Powerup"
appVersion: "1.0.0"

TWILIO_ACCOUNT_SID: ${TWILIO_ACCOUNT_SID}
TWILIO_AUTH_TOKEN: ${TWILIO_AUTH_TOKEN}
TWILIO_FROM_PHONE_NUMBER: ${TWILIO_FROM_PHONE_NUMBER}

